# Generated by Django 3.0 on 2020-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcularter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varible_to_calcular',
            name='resuit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='varible_to_calcular',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='varible_to_calcular',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
