# Generated by Django 3.0 on 2020-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varible_to_Calcular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('Symbol', models.CharField(max_length=100, null=True)),
                ('resuit', models.IntegerField(null=True)),
            ],
        ),
    ]
